version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt || true
  build:
    commands:
      - echo "Ejecutando build..."
      - python --version
      - echo "Build completado"

artifacts:
  files:
    - '**/*'
