version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias"
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Construyendo artefacto"
      - zip -r app.zip .

artifacts:
  files:
    - app.zip
